[versions]
activityCompose = "1.7.2"
kotlin = "1.8.21"
kotlinxCoroutines = "1.7.1"
gson = "2.9.0"
winds = "1.0.0-alpha02"
vanniktech-maven = "0.25.3"
kotlin-jvm = "1.8.21"

[libraries]
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }
kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "kotlinxCoroutines" }
kotlin-gradlePlugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-stdlib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib-jdk8", version.ref = "kotlin" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin-jvm" }
winds = { id = "dev.teogor.winds", version.ref = "winds" }
vanniktech-maven = { id = "com.vanniktech.maven.publish", version.ref = "vanniktech-maven" }
