[versions]
activityCompose = "1.7.2"
kotlin = "1.8.21"
kotlinxCoroutines = "1.7.1"
junitBom = "5.9.1"

[libraries]
activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
gson = { group = "com.google.code.gson", name = "gson", version = "2.8.9" }
kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version = "kotlinxCoroutines" }
kotlin-gradlePlugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-stdlib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib-jdk8", version.ref = "kotlin" }

[plugins]

[bundles]

#[test]
#junit-bom = { group = "org.junit", name = "junit-bom", version = "junitBom" }

#[libraries.test]
#junit-jupiter = { group = "org.junit.jupiter", name = "junit-jupiter" }